#!/usr/bin/env sh

##############
## variable ##
##############
# paths
default_wallpaper="$HOME/.wallpapers/default.png"
bar_launch_script="$HOME/env/config/polybar/launch"

# styling
border_width='2'
border_radius='6'
window_gap='12'
split_ratio='0.56'
borderless_monocle='true'
gapless_monocle='true'
focus_follows_pointer='false'

# colors
focused_border_color='#E95420'
# normal_border_color='#6FE6E4'

## deps
ext_files="$default_wallpaper $bar_launch_script"
ext_commands="bspc xrandr feh xrdb"

##############
## function ##
##############
# $1 = type: command, variable, path
# $2 = name dep to test
exit_if_missing () {
  if [ "$1" = 'command' ]; then 
    [ "$(command -v "$2")" ] || ( printf %s\\n "$2 not found " && exit 1 ) 
  elif [ "$1" = 'variable' ]; then
    [ -n "$2" ] || ( printf %s\\n "$2 not found " && exit 1 )
  elif [ "$1" = 'path' ]; then
    [ -e "$2" ] || ( printf %s\\n "$2 not found " && exit 1 )
  fi
}

check_dependencies () { 
  if [ -n "$ext_files" ]; then
    echo "$ext_files" | tr ' ' '\n' | while read -r i; do
      exit_if_missing 'path' "$i"
    done
  fi

  if [ -n "$ext_commands" ]; then
    echo "$ext_commands" | tr ' ' '\n' | while read -r i; do
      exit_if_missing 'command' "$i"
    done
  fi

  if [ -n "$ext_variables" ]; then 
    echo "$ext_variables" | tr ' ' '\n' | while read -r i; do
      exit_if_missing 'variable' "$i"
    done
  fi
}

# set rules for home hostname
set_home () {
  # set display config
  xrandr --output DVI-D-0 --primary --mode 1920x1080 --rotate normal --rate 144.0 --dpi 92 \
	  --output HDMI-0 --left-of DVI-D-0 --mode 1920x1080 --rotate left --rate 60.0
  
  # add desktops
  bspc monitor 'HDMI-0' -a 'lg_a' 
  bspc monitor 'DVI-D-0' -a 'A' 'B' 'C' 
}

# set rules for katana hostname
set_katana () {
  bspc monitor 'LVDS-1' -a 'A' 'B' 'C' 
}

# set settigs that apply to all
set_common () {

  # remove desktop 'Desktop'
  bspc desktop 'Desktop' -r

  # set bg 
  feh --bg-fill --no-fehbg "$default_wallpaper"

  # remove desktop 'Desktop'
  bspc desktop 'Desktop' -r

  # add config settings
  bspc config  'border_width' "$border_width" 
  bspc config  'border_radius' "$border_radius" # need special build for radius to work  
  bspc config  'window_gap' "$window_gap"  
  bspc config  'split_ratio' "$split_ratio" 
  bspc config  'borderless_monocle' "$borderless_monocle"  
  bspc config  'gapless_monocle' "$gapless_monocle"  
  bspc config  'focus_follows_pointer' "$focus_follows_pointer"  
  bspc config  'click_to_focus' "true"  

  ## set border colors
  bspc config 'focused_border_color' "$focused_border_color"
  bspc config 'normal_border_color' "$normal_border_color"

  # add window rules
  bspc rule -a 'Screenkey' 'manage=off'

  bspc rule -a 'Firefox:Navigator' 'desktop=a' 'state=tiled' 'follow=on' 'border=off' 'focus=on'
  bspc rule -a 'Alacritty' 'state=tiled' 'follow=on' 'border=on' 'focus=on'
  bspc rule -a 'IntelliJ IDEA' 'desktop=b' 'state=tiled' 'follow=on' 'border=off' 'focus=on'
  bspc rule -a 'mpv' 'state=tiled' 'follow=on' 'border=on' 'focus=on'
  bspc rule -a 'polybar-mybar3_DVI-D-0' 'focus=on' 'border=on' 'floating=on'
  bspc rule -a 'Firefox:*' 'focus=on' 'border=on' 'floating=on'
  bspc rule -a 'feh' 'focus=off' 'border=off' 'floating=on' 'layer=below' 'state=floating'
  bspc rule -a 'Pqiv' 'focus=off' 'border=off' 'floating=on' 'layer=below' 'state=floating'
  bspc rule -a 'Ulauncher' 'focus=on' 'border=off' 'floating=on'
}

# start applications when all settings are in place
exit_init () {
  $bar_launch_script & # launch bar 
}

###########
## start ##
###########

if check_dependencies; then
  case "$(hostname)" in
  "home")
      set_home
      ;;
  "home2")
      set_home
      ;;
  "katana")
      set_katana
      ;;
  esac && \
  set_common && exit_init
else 
  printf %s\\n "missing dependency"
fi
