#! /bin/sh

# For home

## Monitor Config ##

getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}

if [ "$(hostname)" = 'home' ]; then 
xrandr --output DP-2 --primary --mode 1920x1080 --rotate normal --rate 144.0 \
--output HDMI-0 --left-of DP-2 --mode 1366x768 --rotate left --rate 60.0
feh --bg-center /usr/home/jesse/resource/wallpapers/1552441584675.png


# create desktops for each monitor 
bspc monitor HDMI-0 -a lg_a
bspc monitor DP-2 -a a b c 

# cleanup desktops
bspc desktop Desktop -r
bspc desktop Desktop -r

bspc rule -a Firefox state=tiled follow=on border=on 
bspc rule -a Alacritty desktop='lg_a' state=tiled follow=on border=on  
bspc rule -a IntelliJ IDEA desktop='b' stated=tiled follow=on border=off focus=on

fi

getcolors

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "$BLACK"

bspc rule -a Screenkey manage=off


## launch bar
$HOME/env/config/polybar/launch.sh
