#!/usr/bin/env sh

set_vol_percentage () {
  amixer set Master "${1}%" >/dev/null 
}

show_vol_percentage () {
  amixer get Master | grep '%' | awk '{ print $4 }'
}

if [ "$(uname)" = 'Linux' ]; then
if [ "$1" = 'vol' ] && [ '+' = "$(echo "$2" | cut -c 1)" ]; then
  new_vol=`expr "$(show_vol_value)" + "$(echo "$2" | cut -c 2-)"`
  set_vol_percentage "$new_vol"
  show_vol_percentage
elif [ "$1" = 'vol' ] && [ '-' = "$(echo "$2" | cut -c 1)" ]; then
  cur_val="$(show_vol_value)"
  decr_val="2"
  new_val=`expr "$cur_val" - "$decr_val"`
  set_vol_percentage "$new_val"
  show_vol_percentage
elif [ "$1" = 'vol' ] && [ -n "$2" ]; then
  set_vol_percentage "$2" 
  show_vol_percentage
elif [ -n "$1" ]; then
  set_vol_percentage "$1"
  show_vol_percentage
else 
  show_vol_percentage
fi
elif [ "$(uname)" = 'FreeBSD' ]; then
  /usr/sbin/mixer "$@"
  dunstify "$(mixer vol | cut -d':' -f2)" --replace=1
fi
