#!/usr/bin/env sh

# record the selected monitor

## Tests ##

command -v mpv >/dev/null \
	||  ( printf "%s\n" "mpv not found" && exit 1 )
command -v youtube-dl >/dev/null \
	|| ( printf "%s\n" "youtube-dl not found" && exit 1 )
[ -z "${SS_DIR}" ] \
	&& ( echo "SS_DIR is not set" && exit 1 )

# vars


FILE_PATH="${SS_DIR}/recording_$(date +%s).webm"
BIT_RATE='30M'

selection=$(xrandr -q \
	| grep ' connected ' \
	| awk '{print $1;}' \
	| rofi  -dmenu -e "select monitor:" \
	       	-location 7 \
		-yoffset -6 -xoffset 163 \
		-show combi \
		-theme-str "#window mainbox inputbar box { index: 0; }")

dims=$(xrandr \
	| grep -w connected \
	| awk -F'[ \+]' '{print $1,$3,$4}' \
	| sed -e 's/primary //' -e 's/ 0//' \
	| grep $selection \
	| sed 's/.* //')

x_offset="$(xrandr -q | grep $selection | cut -d'+' -f2 )" 
y_offset="$(xrandr -q | grep $selection | cut -d'+' -f3 | awk '{print $1}' )" 


ffmpeg -y -f x11grab -r 60 -s \
	$dims -i \
	:0.0+${x_offset},${y_offset} \
	-c:v libvpx -b:v "$BIT_RATE" -c:a libvorbis \
	-threads 0 \
	"${FILE_PATH}"

echo "saved @ -> $FILE_PATH"
echo $FILE_PATH | xclip -selection clipboard
