#!/usr/bin/env sh

SS_DIR="/tmp/screenshot"
mkdir -p "${SS_DIR}"

## Take the SS and save
FILE_NAME="$(date +%s).png"
FILE_PATH="${SS_DIR}/${FILE_NAME}"
grim -g "$(slurp)" $FILE_PATH

echo "screenshot saved @ ${FILE_PATH}" 

# Notify
notify-send -t 5000 'Capture Finished!' "${FILE_PATH}" -i ${FILE_PATH}
  echo $FILE_PATH | tr -d '\n' | xclip -selection clipboard 

# Copy to clipboard
wl-copy < $FILE_PATH
