#!/usr/bin/env zsh
# Sy s
# Display a few stats about system @ current time 
function battery_rem_cap() {
  if [ "$(uname)" = 'FreeBSD' ]; then
    acpiconf -i 0 | grep -i -e "Remaining capacity"
  elif [ "$(uname)" = 'Linux' ]; then 
    cat /sys/class/power_supply/BAT0/capacity 
  fi
} 

function battery_rem_time() {
  acpiconf -i 0 | grep -i -e "Remaining time"
}

function charging_state() {
  if [ "$(uname)" = 'FreeBSD' ]; then
    acpiconf -i 0 | grep -i -e "State"
  elif [ "$(uname)" = 'Linux' ]; then 
    cat /sys/class/power_supply/BAT0/status
  fi
}

function cpu_temp() {
  if [ "$(uname)" = 'FreeBSD' ]; then 
    sysctl dev.cpu | grep -i "temperature" 
  elif [ "$(uname)" = 'Linux' ]; then 
    temp_milli="$(cat /sys/class/thermal/thermal_zone*/temp)"
    temp=`expr $temp_milli / 100`
  fi
}

function cpu_freq() {
  sysctl dev.cpu | grep -i "cpu.0.freq:" 
}


function fan_speed() {
  sysctl dev.acpi_ibm.0.fan_speed
}

function print_info() {
  cpu_freq
  cpu_temp

  if $(acpiconf -i 0 &> /dev/null); then
  charging_state
  battery_rem_cap
  battery_rem_time
  fan_speed
  fi
}

if [ "$1" = "-l" ]; then
  while true; do
    clear
    print_info
    sleep 3  
  done
else 
  print_info
fi

