#!/bin/sh

# plays a youtube video in mpv
# $1 -> the video url

# 6/17 - the yt-dl in the repos is busted right now

prompt_exit () {
  echo $1
  exit 1
}


# checks
command -v mpv >/dev/null 		||  prompt_exit "mpv not found" 
command -v youtube-dl >/dev/null  	||  prompt_exit "youtube-dl not found" 
[ "$#" -eq 1 ]				||  prompt_exit "url required as first arg"

echo "downloading."

mpv --really-quiet \
	-- ytdl-format="((bestvideo[vcodec^=vp9]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio))/best" \
	"$1" \
       	>/dev/null &
