#!/usr/bin/env sh

# open website associated with remote 

BRANCH="$(git branch | grep \* | cut -d ' ' -f2)";
URL="$(git config --get remote.origin.url)/tree/$BRANCH" 
$BROWSER "$(echo $URL | sed 's/\.git//g')"
