#!/usr/local/bin/bash

alias ls='ls -F'
alias ll='ls -lh'
alias lls='ls -lhtr' #Sort by mod fate, show last modified at bottom
#Search
alias rgi='rg -i'

#Info
alias iomon='top -m io -o total'
alias df='df -H'



