#!/usr/bin/env sh

SOCKET="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
DEFAULT_WORKSPACE="A"

echo $DEFAULT_WORKSPACE 

handle() {
   OUTPUT=$(echo $1 | sed  \
     -e '/workspace>>/!d' \
     -e '/[^0-9]*/!d' \
     -e 's/workspace>>//g' |
     tr '12345' 'ABCDE')
   
   if [ "$OUTPUT" = "A" ]; then
     echo $OUTPUT
   fi

   if [ "$OUTPUT" = "B" ]; then
     echo $OUTPUT
   fi

   if [ "$OUTPUT" = "C" ]; then
     echo $OUTPUT
   fi

   if [ "$OUTPUT" = "D" ]; then
     echo $OUTPUT
   fi

   if [ "$OUTPUT" = "E" ]; then
     echo $OUTPUT
   fi
}

nc -U $SOCKET | while read -r line; do handle "$line"; done
