#!/usr/bin/env sh

SOCKET="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
DEFAULT_WORKSPACE="A"

echo $DEFAULT_WORKSPACE 

handle() {
  case $1 in
    workspace\>\>*) echo $1 | sed 's/workspace>>//g' | tr '12345' 'ABCDE' ;;
    workspacev2\>\>) echo $1 | sed 's/workspacev2>>//g' | tr '12345' 'ABCDE' ;;
  esac
}

nc -U $SOCKET | while read -r line; do handle "$line"; done
