#!/usr/bin/env sh

SOCKET="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
DEFAULT_WORKSPACE="A"

echo $DEFAULT_WORKSPACE 

handle() {
   echo $1 | sed  \
     -e '/workspace>>/!d' \
     -e 's/workspace>>//g' |
     tr '12345' 'ABCDE'
}

nc -U $SOCKET | while read -r line; do handle "$line"; done
