#!/usr/bin/env sh

xmodmap -e "keycode 22 = backslash bar backslash bar"
xmodmap -e "keycode 51 = BackSpace BackSpace BackSpace BackSpace"

# Cap lock to control
xmodmap -e "remove Lock = Caps_Lock"
xmodmap -e "remove Control = Control_R"
xmodmap -e "keysym Control_R = Caps_Lock"
xmodmap -e "keysym Caps_Lock = Control_R"
xmodmap -e "add Lock = Caps_Lock"
xmodmap -e "add Control = Control_R"
