~/env/config/x11/bind/map_keys.sh
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr 
xset r rate 260 55
xset dpms 0 0 0 && xset s noblank && xset s off

if [ "$(hostname)" = 'work' ]; then
  eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
  export SSH_AUTH_SOCK
fi

sxhkd &
compton &
dunst &

exec bspwm 
