~/env/config/x11/key_binds # Run script that sets keybinds
~/env/config/x11/settings  # Run script that sets settings

xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr 
sxhkd &

if [ "$(hostname)" = "home" ]; then
  $HOME/resource/app/bsd/compton/compton &
elif [ "$(hostname)" = 'katana' ]; then
  compton &
fi

exec bspwm 

