#!/usr/bin/env sh

bindkey -r "^J"
bindkey -r "^K"
bindkey -r "^L"

bindkey -r "^A"
bindkey "^A" clear-screen

bindkey -r "^I"
bindkey -r "^S"
# bindkey "^S" expand-or-complete
bindkey "\t" expand-or-complete
