#!/usr/local/bin/bash
export EDITOR=vim
export PAGER='less -R'
export BROWSER=firefox
export TERMINAL=alacritty

export LANG=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export CHARSET=UTF-8

# PGP
export GPG_TTY=$(tty)

# Locations
export SCRIPT_DIR="$HOME/env/script/bin"
export XDG_CONFIG_HOME="$HOME/.config"
export XCLIP_PATH=/usr/local/bin/xclip

if [ "$(hostname)" = 'home' ]; then
	export SS_DIR=/disk/work/screenshot
	export DOWNLOAD=/disk/work/downloads
elif [ "$(hostname)" = 'katana' ]; then
	export SS_DIR=/tmp/screenshot
	export DOWNLOAD=/tmp/download
fi

# jdk
if [ $(uname) = "FreeBSD" ]; then
	export JAVA_HOME=/usr/local/openjdk8
elif [ $(uname) = "Linux" ]; then
	export JAVA_HOME='/usr/lib/jvm/java-1.8.0-openjdk-amd64'
fi

# Compilation
export CC=clang
export CXX=clang++
export CMAKE_C_COMPILER=clang
export CMAKE_CXX_COMPILER=clang++

# docker
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/home/jesse/.docker/machine/machines/docker1"
export DOCKER_MACHINE_NAME="docker1"

# node
export NODE_PATH="/home/jesse/.npm/global/lib/node_modules"

# java
export _JAVA_AWT_WM_NONREPARENTING=1
# export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -DactionSystem.xWindow.remove.focus.from.nonFocusable.popups=false -Dsun.java2d.opengl=true'

# app cfg
# exa
export LS_COLORS="di=34:ex=35"

# zsh-z
export ZSHZ_CMD=j
export LIBGIT2_SYS_USE_PKG_CONFIG=1

#firefox
export MOZ_WEBRENDER=1
