#!/usr/bin/env sh

bindkey -r "^S"
bindkey -r "^A"
bindkey "^A" clear-screen
bindkey '^H' backward-char
bindkey '^J' down-line-or-history 
bindkey '^K' up-line-or-history 
bindkey '^L' autosuggest-accept
