#!/usr/bin/env sh

# Info
alias cmd="type -m '*'"

# Misc
alias df='df -H'
alias cls='clear'
alias rgi='rg -i'
alias rgf='rg --files --no-ignore --hidden -g'
alias fd='fd -H' # Search hidden directories by default
alias xclip='xclip -selection clipboard'
alias du='du -sh'
alias ldate='date +"%I:%M %p"'
alias lsblk='lsblk -o NAME,SIZE,TYPE,FSTYPE,LABEL,MOUNTPOINT'

# Overrides
alias ls='exa -1F'
alias ll='exa -llh'
alias tree="exa --long --tree --level=4"
alias cat='bat'
alias neofetch="neofetch --disable Theme --disable Icons --disable Packages"
alias vim='nvim'

# for x230
alias zzz='/usr/local/bin/sudo /usr/sbin/zzz'

# compilation
## Set compilation options up front
alias makecfg='sudo make config-recursive && sudo make install clean' 

# cargo 
alias cargotestbt='RUST_BACKTRACE=1 cargo test -- --nocapture'
alias cargorunbt='RUST_BACKTRACE=1 cargo run'
alias cargotestprint='cargo test -- --nocapture'

# web
alias tb='nc termbin.com 9999 | xclip -selection clipboard'

# docker
alias dockerc='docker compose'
alias docker-c='docker-compose'
alias dockerm='docker-machine'

# mpd
alias music="ncmpcpp"
alias mpc="mpc --host=/tmp/mpd-socket"
