# Created by jesse for 5.6.2

ZSH_CFG_DIR=$HOME/env/zsh
ZSH_MOD_DIR=$HOME/env/zsh/mod

# load funcs
cfg_files=(
    $ZSH_CFG_DIR/zsh_var
    $ZSH_CFG_DIR/zsh_path
    $ZSH_CFG_DIR/zsh_alias
    $ZSH_CFG_DIR/zsh_setting
    $ZSH_CFG_DIR/zsh_bind
)

# compile and load cfg files
for cfg_file ($cfg_files) {
  if [ -f $cfg_file ]; then
    source $cfg_file;
  else
    echo "$cfg_file does not exist"
  fi
}

# load module functions
cfg_modules=(
	${ZSH_MOD_DIR}/z/zsh-z.plugin.zsh
	${ZSH_MOD_DIR}/prompt_j2/prompt_j2_loader
)

for cfg_module ($cfg_modules) {
  if [ -f $cfg_module ]; then
    source $cfg_module;
  else
    echo "$cfg_module does not exist"
  fi
}

# load zsh-autosuggestions
ZSH_AUTOSUGGEST_USE_ASYNC=true;
source "$HOME/env/zsh/mod/zsh-autosuggestions/zsh-autosuggestions.zsh"
