# Created by jesse for 5.6.2

ZSH_CFG_DIR=$HOME/env/zsh
ZSH_MOD_DIR=$HOME/env/zsh/mod

# load funcs
cfg_files=(
    $ZSH_CFG_DIR/zsh_var
    $ZSH_CFG_DIR/zsh_path
    $ZSH_CFG_DIR/zsh_alias
    $ZSH_CFG_DIR/zsh_setting
    $ZSH_CFG_DIR/zsh_bind
)

# compile and load cfg files
for cfg_file ($cfg_files) {
    source $cfg_file;
}

# load module functions
cfg_modules=(
    ${ZSH_MOD_DIR}/z/zsh-z.plugin.zsh
    ${ZSH_MOD_DIR}/zsh-autosuggestions/zsh-autosuggestions.zsh
)

for cfg_module ($cfg_modules) {
    source $cfg_module;
}

# ZSH_AUTOSUGGEST_CONFIG
ZSH_AUTOSUGGEST_USE_ASYNC=true;

# Load prompt
eval "$(starship init zsh)"
