#!/usr/bin/env sh

VPN_SERVICE=openvpn-workVPN
PING_IP=1.1.1.1

is_vpn_connected() {
  systemctl is-active --quiet "$VPN_SERVICE"
}

is_online() {
  ping -c 1 "$PING_IP" > /dev/null 2>&1
}

if is_vpn_connected; then
  echo ""
elif is_online; then
  echo ""
else
  echo "" 
fi
