#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done


CFG_FILE=$HOME/env/config/polybar/bar/desktop
CFG_FILE2=$HOME/env/config/polybar/bar/time
CFG_FILE3=$HOME/env/config/polybar/bar/music
CFG_FILE4=$HOME/env/config/polybar/bar/network

# Launch bar1 and bar2
polybar desktop --config=$CFG_FILE &
polybar time --config=$CFG_FILE2 &
polybar music --config=$CFG_FILE3 &
polybar network --config=$CFG_FILE4

echo "Bars launched..."
