#!/usr/bin/env sh

# get status of mpd

status="$(mpc --host=/tmp/mpd-socket status)"
playing="$(echo $status | grep -i playing)"
paused="$(echo $status | grep -i paused)"
playing_icon=
paused_icon=

if [ -n "$playing" ]; then
	echo "$playing_icon $(mpc --host=/tmp/mpd-socket status | head -n 1)"
elif [ -n "$paused" ]; then
	echo "$paused_icon $(mpc --host=/tmp/mpd-socket status | head -n 1)"
else 
	exit 1
fi
