#!/usr/bin/env sh

online_wifi=" "
online_ethernet=" "
offline=" "

if ifconfig | grep status | tail -n 1 | grep active >/dev/null; then
	if ifconfig | grep -i "wlan" >/dev/null; then
	  echo $online_wifi
	else 
	  echo $online_ethernet
	fi
else
	echo $offline
fi
